name: GitHub Actions for Full-Stack front end

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."